name: chart_sparkline_example
description: A new Flutter application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chart_sparkline:
    path: ../
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
