name: chart_sparkline
description: Beautiful sparkline charts for Flutter.Average line, highest and lowest value.
version: 1.1.0
homepage: https://github.com/biner88/chart_sparkline
issue_tracker: https://github.com/biner88/chart_sparkline/issues
screenshots:
 - description: 'Beautiful Sparkline'
   path: screenshots/sparkline.png
 - description: 'Sparkline averageLine'
   path: screenshots/averageLine.png
 - description: 'Sparkline points last'
   path: screenshots/example_points_last.png
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'
